version: '3'
services:

  postgresinit:
    container_name: senzing-postgresql-init
    environment:
      SENZING_DATABASE_URL: "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-senzing-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-G2}"
      SENZING_SQL_FILES: >-
        /opt/senzing/g2/resources/schema/g2core-schema-postgresql-create.sql
        /app/insert-senzing-configuration.sql
    image: senzing/postgresql-client:${SENZING_DOCKER_IMAGE_VERSION_POSTGRESQL_CLIENT:-latest}
    networks:
      - senzing
    read_only: true
    restart: on-failure

networks:
  senzing:
    external: true
    name: ${SENZING_DOCKER_NETWORK:-senzing-network}
